#!/usr/bin/env bash
# Regenerate Pala_One_2_1/bitter_u8g2_fonts.h from the Bitter variable TTF.
#
# usage: scripts/gen_bitter_fonts.sh BITTER_TTF BDFCONV [OUT_HEADER]
#
#   BITTER_TTF  https://github.com/google/fonts/raw/main/ofl/bitter/Bitter%5Bwght%5D.ttf
#   BDFCONV     built from u8g2's tools/font/bdfconv (plain `make`, no deps)
#   OUT_HEADER  defaults to Pala_One_2_1/bitter_u8g2_fonts.h
#
# Needs uv (for freetype-py). Intermediate BDF/C files go to a temp dir; set
# BDF_DIR to keep the BDFs (e.g. to render preview pages from them).
# See scripts/ttf2bdf.py for what each option does and why.
set -euo pipefail

ttf=$1
bdfconv=$2
here=$(cd "$(dirname "$0")" && pwd)
out=${3:-$here/../Pala_One_2_1/bitter_u8g2_fonts.h}
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# body size | px | word space
# px matches helvR's x-height at that size, and is chosen so the autohinter
# gives every stem the same width (1px at 8-12, 2px at 14; bold one wider).
# Elsewhere it snaps some stems to 1px and some to 2px, so a few letters
# look bold mid-word — check with a full-page render before moving these.
sizes=(
  "08 10.5  4"
  "10 14    5"
  "12 16    5"
  "14 18    6"
)

for row in "${sizes[@]}"; do
  read -r sz px space <<<"$row"
  common=(--px "$px" --space "$space" --min-gap 1)
  uv run -q --with freetype-py python "$here/ttf2bdf.py" "$ttf" "$work/r$sz.bdf" "${common[@]}"
  uv run -q --with freetype-py python "$here/ttf2bdf.py" "$ttf" "$work/b$sz.bdf" "${common[@]}" --wght 700
  for s in r b; do
    "$bdfconv" -f 1 -m '32-126,160-255' -n "u8g2_font_bitter_${s}${sz}_te" \
      -o "$work/$s$sz.c" "$work/$s$sz.bdf" >/dev/null
    python3 "$here/u8g2_set_ascent.py" "$work/$s$sz.bdf" "$work/$s$sz.c" >/dev/null
  done
done

{
  cat <<'EOF'
#pragma once

// Generated by scripts/gen_bitter_fonts.sh — do not edit by hand.
//
// From Bitter (Copyright 2011 The Bitter Project Authors, SIL OFL
// 1.1 — license in bitter_OFL.txt; source
// https://github.com/google/fonts/tree/main/ofl/bitter) into u8g2 font arrays.
// Glyph coverage: ASCII 0x20-0x7E + Latin-1 0xA0-0xFF.
// 1-bit, FreeType-autohinted, wght 400 / 700 of the variable font. Sizes
// match u8g2 Helvetica helvR08/10/12/14's x-height (6/8/9/10 px), with word
// space widened and a 1px minimum gap between glyphs. The ascent byte is
// raised to the ascender height so getFontAscent() covers b/d/l (see
// scripts/u8g2_set_ascent.py). Rendering choices: scripts/ttf2bdf.py.

#include <stdint.h>

#ifndef U8G2_FONT_SECTION
// u8g2 normally defines this (e.g. PROGMEM on AVR/ESP). Include this header after
// U8g2_for_Adafruit_GFX / u8g2 when possible so fonts land in flash.
#define U8G2_FONT_SECTION(fontname)
#endif
EOF
  for row in "${sizes[@]}"; do
    read -r sz _ <<<"$row"
    for s in r b; do echo; cat "$work/$s$sz.c"; done
  done
} >"$out"

if [ -n "${BDF_DIR:-}" ]; then mkdir -p "$BDF_DIR" && cp "$work"/*.bdf "$BDF_DIR"/; fi
echo "wrote $out"
